# Generated by Django 4.2.1 on 2023-05-04 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Empresa', max_length=100)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2023, 5, 4, 20, 52, 18, 982483, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando autorização'), ('ATIVA', 'Ativa, pleno funcionamento'), ('INATIVA', 'Inativa')], default='AGUARDANDO', max_length=25, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
            },
        ),
    ]
