# Generated by Django 4.2.1 on 2023-05-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_data_criacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
        migrations.AlterModelTable(
            name='empresa',
            table=None,
        ),
    ]
